---
abstract: 'Edit and validate dpkg source files with cme'
author:
  - 'Dominique Dumont (dod at debian dot org)'
build_requires:
  Config::Model::Tester: 2.043
  File::Slurp: 2.07
  Module::Build: 0.34
  Path::Class: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::Memory::Cycle: 0
  Test::More: 0
  Test::Warn: 0.11
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.132140'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Model-Dpkg
provides:
  Config::Model::Backend::Dpkg:
    file: lib/Config/Model/Backend/Dpkg.pm
  Config::Model::Backend::Dpkg::Control:
    file: lib/Config/Model/Backend/Dpkg/Control.pm
  Config::Model::Backend::Dpkg::Copyright:
    file: lib/Config/Model/Backend/Dpkg/Copyright.pm
  Config::Model::Backend::Dpkg::Patch:
    file: lib/Config/Model/Backend/Dpkg/Patch.pm
  Config::Model::Backend::DpkgSyntax:
    file: lib/Config/Model/Backend/DpkgSyntax.pm
  Config::Model::Dpkg:
    file: lib/Config/Model/Dpkg.pm
    version: 2.040
  Config::Model::Dpkg::Dependency:
    file: lib/Config/Model/Dpkg/Dependency.pm
requires:
  AnyEvent: 0
  AnyEvent::HTTP: 0
  Config::Model: 2.041
  DB_File: 0
  File::Path: 2.07
  IO::File: 0
  Log::Log4perl: 1.11
  Mouse: 0
  Parse::RecDescent: v1.90.0
  Software::License: 0
  namespace::autoclean: 0
resources:
  MailingList: https://lists.sourceforge.net/lists/listinfo/config-model-users
  homepage: https://github.com/dod38fr/config-model/wiki
  license: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
  repository: git://anonscm.debian.org/pkg-perl/packages/libconfig-model-dpkg-perl.git
version: 2.040
